-- Перелік форми 3/Прод із прив'язкою до номенклатури.
-- Згенеровано build/make_form3_seed.py — не редагувати вручну.
-- Джерело: бланк звіту-заявки 3/Прод за 2026 рік, аркуш «звіт ф3».
-- Штат частини за цим бланком — окремим сідом (form3_norms.sql), у поставку він не входить.

INSERT INTO report_form(code, name) VALUES('3/Прод', 'Звіт-заявка про наявність і потребу в технічних засобах');

-- Розділи й позиції в порядку бланка.
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Кухні причіпні', NULL, 10;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'КП-130 (КП-130 М)', 'Кухні причіпні', 20;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Кухні переносні', NULL, 30;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'КО-75', 'Кухні переносні', 40;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Піл польова "Варя"', 'Кухні переносні', 50;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Піч польова "АУЛ-25 літрів"', 'Кухні переносні', 60;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Піч польова "АУЛ-50 літрів"', 'Кухні переносні', 70;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'КИП''ЯТИЛЬНИКИ ПЕРЕНОСНІ', NULL, 80;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ПНК-2', 'КИП''ЯТИЛЬНИКИ ПЕРЕНОСНІ', 90;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Плити', NULL, 100;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ПП-40', 'Плити', 110;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ПП-170', 'Плити', 120;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ТЕРМОСИ', NULL, 130;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ТВН-12', 'ТЕРМОСИ', 140;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ТН-36', 'ТЕРМОСИ', 150;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ПРИЧІПИ-ФУРГОНИ ІЗОТЕРМІЧНІ', NULL, 160;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ГЗСА-896 (ОАР-2)', 'ПРИЧІПИ-ФУРГОНИ ІЗОТЕРМІЧНІ', 170;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'КОНТЕЙНЕР ІЗОТЕРМІЧНИЙ', NULL, 180;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'КІ-50', 'КОНТЕЙНЕР ІЗОТЕРМІЧНИЙ', 190;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'АВТОМОБІЛІ-ЦИСТЕРНИ ДЛЯ ВОДИ', NULL, 200;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'АВЦ-1,7', 'АВТОМОБІЛІ-ЦИСТЕРНИ ДЛЯ ВОДИ', 210;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ПРИЧІПИ-ЦИСТЕРНИ ДЛЯ ВОДИ', NULL, 220;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ЦВ-1,2 (ЦВ-50)', 'ПРИЧІПИ-ЦИСТЕРНИ ДЛЯ ВОДИ', 230;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ЦВ-4', 'ПРИЧІПИ-ЦИСТЕРНИ ДЛЯ ВОДИ', 240;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'ЄМНІСТЬ ДЛЯ ВОДИ ХАРЧОВА', NULL, 250;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Ємність харчова 1000 л.', 'ЄМНІСТЬ ДЛЯ ВОДИ ХАРЧОВА', 260;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'РІЗНЕ', NULL, 270;
INSERT INTO report_line(form_id, name, section, sort) SELECT (SELECT id FROM report_form WHERE code='3/Прод'), 'Пристрій для приготування їжі', 'РІЗНЕ', 280;

-- Коди служби під позиціями форми.
--   КП-130 (КП-130 М): 33 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10101'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10101');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10102'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10102');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10103'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10103');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10104'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10104');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10105'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10105');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10106'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10106');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10107'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10107');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10108'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10108');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10109'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10109');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10110'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10110');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10111'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10111');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10112'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10112');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10113'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10113');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10114'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10114');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10115'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10115');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10116'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10116');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10117'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10117');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10118'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10118');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10119'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10119');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10120'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10120');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10121'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10121');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10122'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10122');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10123'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10123');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10124'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10124');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10125'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10125');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10126'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10126');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10127'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10127');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10128'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10128');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10129'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10129');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10130'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10130');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10131'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10131');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10132'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10132');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10133'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КП-130 (КП-130 М)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10133');
--   КО-75: 1 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10134'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='КО-75') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10134');
--   Піл польова "Варя": 1 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10003'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Піл польова "Варя"') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10003');
--   Піч польова "АУЛ-25 літрів": 1 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10004'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Піч польова "АУЛ-25 літрів"') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10004');
--   Піч польова "АУЛ-50 літрів": 1 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10005'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Піч польова "АУЛ-50 літрів"') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10005');
--   ТВН-12: 3 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10201'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ТВН-12') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10201');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10202'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ТВН-12') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10202');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10205'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ТВН-12') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10205');
--   ТН-36: 3 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10203'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ТН-36') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10203');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10204'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ТН-36') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10204');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10206'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ТН-36') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10206');
--   ЦВ-1,2 (ЦВ-50): 5 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10303'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-1,2 (ЦВ-50)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10303');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10304'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-1,2 (ЦВ-50)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10304');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10305'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-1,2 (ЦВ-50)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10305');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10306'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-1,2 (ЦВ-50)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10306');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10307'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-1,2 (ЦВ-50)') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10307');
--   ЦВ-4: 3 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10301'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-4') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10301');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10302'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-4') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10302');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10308'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='ЦВ-4') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10308');
--   Ємність харчова 1000 л.: 6 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10089'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Ємність харчова 1000 л.') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10089');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10094'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Ємність харчова 1000 л.') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10094');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10095'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Ємність харчова 1000 л.') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10095');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10096'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Ємність харчова 1000 л.') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10096');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10512'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Ємність харчова 1000 л.') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10512');
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10608'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Ємність харчова 1000 л.') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10608');
--   Пристрій для приготування їжі: 1 кодів
INSERT INTO nomen_report_line(nomen_id, report_line_id) SELECT (SELECT id FROM nomen WHERE code='10001'), (SELECT rl.id FROM report_line rl JOIN report_form f ON f.id = rl.form_id WHERE f.code='3/Прод' AND rl.name='Пристрій для приготування їжі') WHERE EXISTS (SELECT 1 FROM nomen WHERE code='10001');
